SELECT TP.SABOR, NF.DATA_VENDA, INF.QUANTIDADE
FROM tabela_de_produtos TP
INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais NF ON INF.NUMERO = NF.NUMERO;

# AMOUNT SOLD BY FLAVOR ON 2016
SELECT TP.SABOR, YEAR(NF.DATA_VENDA) AS YEAR, SUM(INF.QUANTIDADE) AS AMOUNT
FROM tabela_de_produtos TP
INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais NF ON INF.NUMERO = NF.NUMERO
WHERE  YEAR(NF.DATA_VENDA) = 2016
GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)
ORDER BY TP.SABOR DESC ;

 # TOTAL SOLD ON 2016
SELECT YEAR(NF.DATA_VENDA) AS YEAR, SUM(INF.QUANTIDADE) AS AMOUNT
FROM tabela_de_produtos TP
INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais NF ON INF.NUMERO = NF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY YEAR(NF.DATA_VENDA);

SELECT FLAVOR_SOLD.SABOR, FLAVOR_SOLD.YEAR, FLAVOR_SOLD.AMOUNT AS AMOUNT_SOLD,
       ROUND((FLAVOR_SOLD.AMOUNT / TOTAL_SOLD.AMOUNT) * 100, 2) AS PERCENTAGE
FROM (
    SELECT TP.SABOR, YEAR(NF.DATA_VENDA) AS YEAR, SUM(INF.QUANTIDADE) AS AMOUNT
    FROM tabela_de_produtos TP
    INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
    INNER JOIN notas_fiscais NF ON INF.NUMERO = NF.NUMERO
    WHERE  YEAR(NF.DATA_VENDA) = 2016
    GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)
    ORDER BY TP.SABOR DESC
    ) AS FLAVOR_SOLD
INNER JOIN (
    SELECT YEAR(NF.DATA_VENDA) AS YEAR, SUM(INF.QUANTIDADE) AS AMOUNT
    FROM tabela_de_produtos TP
    INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
    INNER JOIN notas_fiscais NF ON INF.NUMERO = NF.NUMERO
    WHERE YEAR(NF.DATA_VENDA) = 2016
    GROUP BY YEAR(NF.DATA_VENDA)
    ) AS TOTAL_SOLD
ON FLAVOR_SOLD.YEAR = TOTAL_SOLD.YEAR
ORDER BY PERCENTAGE DESC;