CREATE TABLE TAB_IDENTITY
	(ID INT AUTO_INCREMENT, DESCRIPTOR VARCHAR(20), PRIMARY KEY(ID));

INSERT INTO TAB_IDENTITY (DESCRIPTOR) VALUES ('CUSTOMER1');
INSERT INTO TAB_IDENTITY (DESCRIPTOR) VALUES ('CUSTOMER2');
INSERT INTO TAB_IDENTITY (DESCRIPTOR) VALUES ('CUSTOMER3');

SELECT * FROM TAB_IDENTITY;

DELETE FROM TAB_IDENTITY WHERE ID = 3;
INSERT INTO TAB_IDENTITY (DESCRIPTOR) VALUES ('CUSTOMER4');
INSERT INTO TAB_IDENTITY (ID, DESCRIPTOR) VALUES (100, 'CUSTOMER5');
INSERT INTO TAB_IDENTITY (DESCRIPTOR) VALUES ('CUSTOMER6');

SELECT * FROM TAB_IDENTITY;