DELIMITER $
CREATE TRIGGER TG_CALCULATE_BILLING_INSERT AFTER UPDATE ON notes_items
    FOR EACH ROW BEGIN
        DELETE FROM tab_billing;
        INSERT INTO tab_billing
            SELECT A.SALE_DATE, SUM(B.AMOUNT * B.PRICE) AS TOTAL_SALE
            FROM notes A INNER JOIN notes_items B
            ON A.NUMBER = B.NUMBER
            GROUP BY A.SALE_DATE;
END $

DELIMITER $
CREATE TRIGGER TG_CALCULATE_BILLING_INSERT AFTER DELETE ON notes_items
    FOR EACH ROW BEGIN
        DELETE FROM tab_billing;
        INSERT INTO tab_billing
            SELECT A.SALE_DATE, SUM(B.AMOUNT * B.PRICE) AS TOTAL_SALE
            FROM notes A INNER JOIN notes_items B
            ON A.NUMBER = B.NUMBER
            GROUP BY A.SALE_DATE;
END $