# Testing ROLLBACK
START TRANSACTION;

SELECT * FROM sellers;

UPDATE sellers SET  COMMISSION = COMMISSION * 1.15;

ROLLBACK;

SELECT * FROM sellers;

# Testing COMMIT
START TRANSACTION;

SELECT * FROM sellers;

UPDATE sellers SET  COMMISSION = COMMISSION * 1.15;

COMMIT;

SELECT * FROM sellers;