SELECT * FROM sellers;

SELECT * FROM sucos_vendas.tabela_de_vendedores;

SELECT * FROM sellers A
INNER JOIN sucos_vendas.tabela_de_vendedores B
ON A.REGISTRATION = SUBSTRING(B.MATRICULA,3,3);

UPDATE sellers A INNER JOIN  sucos_vendas.tabela_de_vendedores B
ON A.REGISTRATION = SUBSTRING(B.MATRICULA,3,3)
SET A.VACATIONS = B.DE_FERIAS;

SELECT A.CPF FROM customer A
INNER JOIN sellers B
ON A.NEIGHBOURHOOD = B.NEIGHBOURHOOD;

UPDATE customer A INNER JOIN sellers B
ON A.NEIGHBOURHOOD = B.NEIGHBOURHOOD
SET A.VOLUME_PURCHASE = A.VOLUME_PURCHASE * 1.30;