USE `sucos_vendas`;
DROP procedure IF EXISTS `Comparativo_Vendas`;

DELIMITER $$
USE `sucos_vendas`$$
CREATE PROCEDURE `Comparativo_Vendas` (vData1 DATE, vData2 DATE)
BEGIN
	DECLARE TOTAL_VENDA_DATA1 DATE;
	DECLARE TOTAL_VENDA_DATA2 DATE;
	DECLARE variacao DECIMAL(10,2);
	DECLARE msgErro VARCHAR(30);

	DECLARE CONTINUE HANDLER for 1339 SET msgErro = 'Não há essa opção';

	SELECT SUM(B.QUANTIDADE * B.PRECO) INTO TOTAL_VENDA_DATA1  FROM
	NOTAS_FISCAIS A INNER JOIN ITENS_NOTAS_FISCAIS B
	ON A.NUMERO = B.NUMERO
	WHERE A.DATA_VENDA = vData1;

	SELECT SUM(B.QUANTIDADE * B.PRECO) INTO TOTAL_VENDA_DATA2  FROM
	NOTAS_FISCAIS A INNER JOIN ITENS_NOTAS_FISCAIS B
	ON A.NUMERO = B.NUMERO
	WHERE A.DATA_VENDA = vData2;

	SET variacao = ((TOTAL_VENDA_DATA1 / TOTAL_VENDA_DATA2) -1) * 100;

	CASE
		WHEN variacao > 10 THEN
			SELECT 'Verde';
		WHEN variacao <= 10 AND variacao >= -10 THEN
			SELECT 'Amarela';
		WHEN variacao < -10 THEN
			SELECT 'Vermelho';
	END CASE;
	SELECT msgErro;
END$$

DELIMITER ;