USE `sucos_vendas`;
DROP procedure IF EXISTS `sucos_vendas`.`Soma_Dias_Notas`;

DELIMITER $$
USE `sucos_vendas`$$
CREATE PROCEDURE `Soma_Dias_Notas`()
BEGIN
	DECLARE DATAINICIAL DATE;
	DECLARE DATAFINAL DATE;
	DECLARE NUMNOTAS INT;
	SET DATAINICIAL = '20170101';
	SET DATAFINAL = '20170110';
	WHILE DATAINICIAL <= DATAFINAL
	DO
		SELECT COUNT(*) INTO NUMNOTAS
		FROM notas_fiscais WHERE DATA_VENDA = DATAINICIAL;
		SELECT concat(DATE_FORMAT(DATAINICIAL, '%d/%m/%Y'), '-' ,
		CAST(NUMNOTAS as CHAR(50)));
		SELECT ADDDATE(DATAINICIAL, INTERVAL 1 DAY) INTO DATAINICIAL;
	END WHILE;

END$$

DELIMITER ;