SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMIT_SUM FROM tabela_de_clientes
GROUP BY ESTADO;

# It not works, Cause we have to use HAVING TO for GROUPS
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMIT_SUM FROM tabela_de_clientes
WHERE LIMIT_SUM > 900000
GROUP BY ESTADO;
#Correct way:
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMIT_SUM FROM tabela_de_clientes
GROUP BY ESTADO
HAVING LIMIT_SUM < 900000;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MOST_EXPENSIVE, MIN(PRECO_DE_LISTA) AS CHEAPER
FROM tabela_de_produtos
GROUP BY EMBALAGEM HAVING SUM(PRECO_DE_LISTA) <= 80;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MOST_EXPENSIVE, MIN(PRECO_DE_LISTA) AS CHEAPER
FROM tabela_de_produtos
GROUP BY EMBALAGEM
HAVING SUM(PRECO_DE_LISTA) <= 80 AND MAX(PRECO_DE_LISTA) >= 5;

SELECT CPF, COUNT(*) FROM notas_fiscais
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY CPF
HAVING COUNT(*) > 2000
