USE vendas_sucos;

CREATE TABLE sales_table
(
    NUMBER VARCHAR(5) NOT NULL,
    SALE_DATE DATE NULL,
    CPF VARCHAR(11) NOT NULL,
    REGISTRATION VARCHAR(5) NOT NULL,
    TAX FLOAT NULL,
    PRIMARY KEY (NUMBER)
);

ALTER TABLE sales_table ADD CONSTRAINT FK_CUSTOMERS
FOREIGN KEY (CPF) REFERENCES customer(CPF);

ALTER TABLE sales_table ADD CONSTRAINT FK_SELLERS
FOREIGN KEY (REGISTRATION) REFERENCES sellers(REGISTRATION);