SELECT  CURDATE();

SELECT CURRENT_TIME();

SELECT CURRENT_TIMESTAMP();

SELECT YEAR(CURRENT_TIMESTAMP());

SELECT DAY(CURRENT_TIMESTAMP());

SELECT MONTH(CURRENT_TIMESTAMP());

SELECT MONTHNAME(CURRENT_TIMESTAMP());

SELECT DATEDIFF(CURRENT_TIMESTAMP(), '2003-05-16') AS MY_TIME_ALIVE;

SELECT CURRENT_TIMESTAMP() AS TODAY_DAY,
       DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 DAY) AS RESULT;

# Using with TABLES
SELECT DISTINCT DATA_VENDA,
                DAYNAME(DATA_VENDA) AS DAY, MONTHNAME(DATA_VENDA) AS MOUNTH,
                YEAR(DATA_VENDA)
FROM notas_fiscais;

SELECT COUNT(DATA_VENDA) AS N_NOTES, DATA_VENDA,
                DAYNAME(DATA_VENDA) AS DAY, MONTHNAME(DATA_VENDA) AS MOUNTH,
                YEAR(DATA_VENDA)
FROM notas_fiscais
GROUP BY DATA_VENDA;

SELECT NOME, TIMESTAMPDIFF (YEAR, DATA_DE_NASCIMENTO, CURDATE()) AS    IDADE
FROM  tabela_de_clientes
