SELECT LTRIM('         OLA') AS RESULT;

SELECT RTRIM('OLA         ') AS RESULT;

SELECT TRIM ('     OLA    ') AS RESULT;

SELECT CONCAT('OLA', '', 'TUDO BEM', '?')AS RESULT;

# UPPERCASE
SELECT UPPER('ola tudo bem?') AS RESULT;

# LOWERCASE
SELECT LOWER('OLA TUDO BEM?') AS RESULT;

# SUBSTRING
SELECT SUBSTRING('OLA, TUDO BEM?', 6) AS RESULT;
SELECT SUBSTRING('OLA, TUDO BEM?', 6, 4) AS RESULT;

# using on QUERIES
SELECT CONCAT(NOME, ' (', CPF, ') ') AS RESULT FROM tabela_de_clientes;

SELECT NOME, CONCAT(ENDERECO_1, ' ', BAIRRO, ' ', CIDADE, ' ', ESTADO) AS COMPLETO
FROM tabela_de_clientes