USE `sucos_vendas`;
DROP procedure IF EXISTS `Limite_creditos`;

DELIMITER $$
USE `sucos_vendas`$$
CREATE PROCEDURE `Limite_creditos`()
BEGIN
	DECLARE LIMITECREDITO FLOAT;
	DECLARE LIMITECREDITOACUM FLOAT;
	DECLARE fim_do_cursor INT;

	DECLARE c CURSOR FOR SELECT LIMITE_DE_CREDITO FROM Tabela_de_Clientes;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET fim_do_cursor = 1;

	SET fim_do_cursor = 0;
	SET LIMITECREDITOACUM = 0;
	SET LIMITECREDITO = 0;

	OPEN c;
	WHILE fim_do_cursor = 0
	DO
		FETCH c INTO LIMITECREDITO;
		IF fim_do_cursor = 0 THEN
			SET LIMITECREDITOACUM = LIMITECREDITOACUM + LIMITECREDITO;
		END IF;
	END WHILE;
	SELECT LIMITECREDITOACUM;
	CLOSE c;
END$$

DELIMITER ;