USE vendas_sucos;

CREATE TABLE PRODUCTS
(
    CODE VARCHAR(10) NOT NULL,
    DESCRIPTOR VARCHAR(100) NULL,
    FLAVOUR VARCHAR(50) NULL ,
    SIZE VARCHAR(50) NULL ,
    PACKAGING VARCHAR(50) NULL ,
    PRICE_LIST FLOAT NULL,
    PRIMARY KEY (CODE)
);

CREATE TABLE SELLERS
(
    REGISTRATION VARCHAR(5) NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NULL,
    NEIGHBOURHOOD VARCHAR(50) NULL,
    COMMISSION FLOAT NULL,
    ADMISSION_DATE DATE NULL,
    VACATIONS BIT(1) NULL
);

CREATE TABLE CUSTOMER (
  CREL_PO VARCHAR(11) PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  ADDRESS VARCHAR(150) NOT NULL,
  NEIGHBOURHOOD VARCHAR(50) NOT NULL,
  CITY VARCHAR(50) NOT NULL,
  STATE VARCHAR(50) NOT NULL,
  POSTCODE VARCHAR(8) NOT NULL,
  DATE_BORN DATE NOT NULL,
  AGE INT NOT NULL,
  GENDER VARCHAR(1) NOT NULL,
  CREDIT_LIMIT FLOAT NOT NULL,
  VOLUME_PURCHASE FLOAT NOT NULL,
  FIRST_PURCHASE BOOLEAN NOT NULL
);

ALTER TABLE CUSTOMER RENAME COLUMN CREL_PO TO CPF;