SELECT * FROM tabela_de_clientes;

SELECT ESTADO, LIMITE_DE_CREDITO FROM tabela_de_clientes;

# They Don't work Without GROUP BY

#MIN
SELECT ESTADO, MIN(LIMITE_DE_CREDITO) FROM tabela_de_clientes GROUP BY ESTADO;

#MAX()
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS 'Total Limit' FROM tabela_de_clientes
GROUP BY ESTADO;


SELECT EMBALAGEM, PRECO_DE_LISTA FROM tabela_de_produtos;
#MAX()
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS 'Most Expensive' FROM tabela_de_produtos
GROUP BY EMBALAGEM;

#COUNT()
SELECT EMBALAGEM, COUNT(*) AS 'COUNT' FROM tabela_de_produtos
GROUP BY EMBALAGEM;

SELECT BAIRRO, SUM(LIMITE_DE_CREDITO) AS 'Credit Limit' FROM tabela_de_clientes
WHERE CIDADE = 'RIO DE JANEIRO' GROUP BY BAIRRO;

SELECT ESTADO, BAIRRO, SUM(LIMITE_DE_CREDITO) AS 'Credit Limit' FROM tabela_de_clientes
WHERE CIDADE = 'RIO DE JANEIRO'
GROUP BY BAIRRO, ESTADO;

SELECT ESTADO, BAIRRO, SUM(LIMITE_DE_CREDITO) AS 'Credit Limit' FROM tabela_de_clientes
WHERE CIDADE = 'RIO DE JANEIRO'
GROUP BY BAIRRO, ESTADO
ORDER BY ESTADO, BAIRRO;