SELECT * FROM tabela_de_produtos;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
CASE
    WHEN PRECO_DE_LISTA >= 12 THEN 'EXPENSIVE PRODUCT'
    WHEN PRECO_DE_LISTA  >= 7 AND PRECO_DE_LISTA  < 12 THEN 'WORTH PRODUCT'
    ELSE 'CHEAP PRODUCT'
END AS PRICE_STATUS
FROM tabela_de_produtos;

SELECT EMBALAGEM,
CASE
    WHEN PRECO_DE_LISTA >= 12 THEN 'EXPENSIVE PRODUCT'
    WHEN PRECO_DE_LISTA  >= 7 AND PRECO_DE_LISTA  < 12 THEN 'WORTH PRODUCT'
    ELSE 'CHEAP PRODUCT'
END AS PRICE_STATUS, AVG(PRECO_DE_LISTA) AS AVARAGE_PRICE
FROM tabela_de_produtos
GROUP BY EMBALAGEM, CASE
    WHEN PRECO_DE_LISTA >= 12 THEN 'EXPENSIVE PRODUCT'
    WHEN PRECO_DE_LISTA  >= 7 AND PRECO_DE_LISTA  < 12 THEN 'WORTH PRODUCT'
    ELSE 'CHEAP PRODUCT'
END
ORDER BY EMBALAGEM;

SELECT EMBALAGEM,
CASE
    WHEN PRECO_DE_LISTA >= 12 THEN 'EXPENSIVE PRODUCT'
    WHEN PRECO_DE_LISTA  >= 7 AND PRECO_DE_LISTA  < 12 THEN 'WORTH PRODUCT'
    ELSE 'CHEAP PRODUCT'
END AS PRICE_STATUS, AVG(PRECO_DE_LISTA) AS AVARAGE_PRICE
FROM tabela_de_produtos
WHERE SABOR = 'MANGA'
GROUP BY EMBALAGEM, CASE
    WHEN PRECO_DE_LISTA >= 12 THEN 'EXPENSIVE PRODUCT'
    WHEN PRECO_DE_LISTA  >= 7 AND PRECO_DE_LISTA  < 12 THEN 'WORTH PRODUCT'
    ELSE 'CHEAP PRODUCT'
END
ORDER BY EMBALAGEM;


SELECT NOME, YEAR(DATA_DE_NASCIMENTO) AS BIRTH_YEAR,
CASE
    WHEN YEAR(DATA_DE_NASCIMENTO) < 1990 THEN 'Old person'
    WHEN YEAR(DATA_DE_NASCIMENTO) >= 1990 AND YEAR(DATA_DE_NASCIMENTO) <= 1995 THEN 'Young person'
    ELSE 'Child'
END AS 'CLASS'
FROM tabela_de_clientes
ORDER BY DATA_DE_NASCIMENTO;

